### ISSUE TITLE
SWD debug

### ISSUE THREAD

**Issue by papyDoctor** [gdobato/portenta-h7#3]
Please, can you clarify this:
"Make sure you do not override the Arduino bootloader since it is needed for some early stage initializations, like the PMIC configuration. Overriding Arduino bootloader could lead to a bricked board. Use this project at your own risk."
To my knowledge, using a DAP access cannot brick anything since even if a first bootloader is erased, it can be reflashed via the SWD DAP access.
Or is the chip used has special features?

**Comment by gdobato** [comment]
Hello @papyDoctor ,
The Portenta-H7 has a Power Management IC which needs to be configured at the very early phase to feed up some power domains, including the one for the DAP access. This is done by the official Arduino Bootloader which is flashed on all boards. 

If you flash the example of this project there should not be any problem, at least a known one, as long as you do not modifiy [memory](https://github.com/gdobato/portenta-rs/blob/master/memory.x#L3-L11) since the Arduino Bootloader keeps untouched in this project ( located at 0x08000000).

**Comment by gdobato** [comment]
I will update the README.md to clarify this point. Thanks for the feedback :)

**Comment by gdobato** [comment]
documentation updated.
